Add tests for socketio server.
vodwatch/vodwatch_backend pull request #27
Opened 2022-06-30 12:44 UTC by juliasch5

2022-07-02 09:51 UTC, piotr-tomczyk requested changes
Trzeba jeszcze dodać w ```requirements.txt``` pytest i dodać sekcję w ```README.md``` o tym jak odpalić testy. Potem może dodać skrypty na windowsa i linuxa aby odpalał main.py i testy od razu.

2022-07-02 09:51 UTC, piotr-tomczyk commented on .gitignore
> +.pytest_cache
Dodać do gitignore folder pycache

2022-07-08 03:21 UTC, piotr-tomczyk approved these changes
Looks Ok Now

2022-07-08 06:39 UTC, Mich519 approved these changes
Nice

2022-07-09 09:18 UTC, merged