31 zmiana logiki przechowywania informacji na temat pokoi użytkowników permisji
vodwatch/vodwatch_backend pull request #33
Opened 2022-07-30 10:09 UTC by Mich519

2022-08-05 18:03 UTC, juliasch5 requested changes

2022-08-05 18:03 UTC, juliasch5 commented on src/main.py
> +        })
Shouldn't it be `to=sid`, so it will be sent only to the user that created that room?

2022-08-05 18:03 UTC, juliasch5 commented on src/main.py
> +        })
Here should be `to=sid`, so it won't be sent to all users connected to the server.

2022-08-13 09:18 UTC, piotr-tomczyk approved these changes

2022-08-13 09:18 UTC, piotr-tomczyk commented on src/main.py
> +    room_dict[roomId][sid]['permissions'] = PERMISSIONS_USER.copy()
można zrobić const PERMISSIONS zamiast stringa 'permissions'

2022-08-13 09:18 UTC, piotr-tomczyk commented on src/main.py
> +        'roomId': roomId,
można zrobić const ROOM_ID

2022-08-13 09:18 UTC, piotr-tomczyk commented on src/main.py
>  def find_room_by_client(sid):
Trzeba pomyśleć co zrobić z tą funkcją, ale z tego co pamiętam to już jej nie używamy

2022-08-13 09:18 UTC, merged